name: Build SRS Rule-Set

# Скрипт будет запускаться при каждом изменении файла adult.lst
# и его можно будет запустить вручную (workflow_dispatch)
on:
  push:
    paths:
      - 'adult.lst'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Настройка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Конвертация LST в JSON
        run: python convert.py

      - name: Скачивание и установка sing-box
        run: |
          wget https://github.com/SagerNet/sing-box/releases/download/v1.10.1/sing-box-1.10.1-linux-amd64.tar.gz
          tar -xzf sing-box-1.10.1-linux-amd64.tar.gz
          mv sing-box-*/sing-box ./sing-box
          chmod +x sing-box

      - name: Компиляция SRS
        run: ./sing-box rule-set compile adult.json -o adult.srs

      - name: Отправка готового SRS в репозиторий
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add adult.srs
          # Если изменений нет, скрипт не выдаст ошибку
          git commit -m "Автоматическая сборка adult.srs" || echo "Нет изменений для коммита"
          git push

